### PR TITLE
Notes and Boons tabs to character sheet

### PR DESCRIPTION
**Pull request by Veichassur**
Notes page similar to general description pages (like Equipment)
Boons page similar to other feature lists
New boon item type with name, description, boontype fields

### CODE REVIEW

**Comment by Veichassur** [comment]
image

**Comment by Rayji96** [comment]
Can you reorder boon to fall after Features?
As well I think Notes might fit under Description as well.
What do you think? I want to avoid too many tabs haha :)

**Comment by Veichassur** [comment]
I totally agree, too many tabs will be confusing to players.
So maybe Boons under the Features tab, but at the top of the page?
And rename equipment tab to Other and put the notes there?
At least in my games these things should be used quite frequently, so I
would like easy access to them. :)

**Comment by Veichassur** [comment]
How about this?
I went ahead and also added a new feature type: Background; which is somewhat different from merits/flaws.
image

**Review by Rayji96 — APPROVED** [review]

**Pull request merged**
