### PR TITLE
Sass Conversion + Minor CSS adjustments

### PR DESCRIPTION
**Pull request by apriltaoyvr**
Converting to SCSS, changing chat card BGs to character sheet BG, fixing some alignment issues in character + item sheets

**General Tidying**
- Refactoring CSS to SCSS
- Assigned commonly repeated colours to variables
- Cleaned up most of the flex CSS in character and item sheets 

**Fixes**
- Removed a class declaration in the ghoul sheet causing the exp div to be there twice
- Centered the / between the EXP inputs
- Corrected missing space between item image and title
image

**Aesthetic Changes**
- Smaller name/clan/predator input boxes
- Lock button and actor image are closer/more merged
- Changed black border around actor image to matching red border

image

- Colouring chat card BG to match inventory sheet BG
- Changed header text from Roboto to Cormorant Light

image

- Active item tab text shadow + underline

image

- Textbox input borders not visible for Description textbox inputs

image

### CODE REVIEW

**Comment by Rayji96** [comment]
Please rebase off/solve merge conflicts with the dev branch :)
Can you also post screenshots of UI changes?

**Comment by CasanovaSekova** [comment]
Sure, give me a bit to merge conflicts

Alignment fixes:
Colouring chat card BG to match inventory sheet BG, changed text from Roboto to Cormorant Light
image

Adding margins between the item image and item name:
image

Aesthetic changes:
Made the name/clan/predator input boxes smaller, tiny visual adjustment so that lock button, actor image are closer/more merged, additional margin/padding for most of the character stats in header for PC character sheets
image

Active item tab text shadow, can revert if necessary
image

**Comment by CasanovaSekova** [comment]
Okay! Sorry for all the trouble / waffling with github. Definitely still getting used to everything and thank you for your patience. All the aesthetic changes are above, The recent commits from the others should be included in SCSS format with this now too.

**Comment by Rayji96** [comment]
linter failures :(
is the current css generated by the scss? we can change the rules to only lint scss

**Comment by CasanovaSekova** [comment]
Yeah, it's all generated from the scss. That would be lovely if you can adjust the linter for it. Do you need/want autoprefixer for it or would it make the linter unhappy?

**Comment by Rayji96** [comment]
I just noticed, description textboxes have a small sliver of white for where the text background is in the screenshot. Is that still there? If so can you add like a min width and height or something so that the white background fills the space?

**Comment by CasanovaSekova** [comment]
Sure, I can do that. What I'll do is make the input bg transparent for boxes so they blend in with the sheets better.

**Comment by Rayji96** [comment]
I'll see what I can do to fix those sass linter issues.
Sorry for the late review, was on vacation!

**Comment by AucaCoyan** [comment]
Hi! I would love to see SCSS files! Are there any news of the linter? Just asking, is it necessary to lint files generated by `sass` ?
Thanks! would like to help if there is any need

**Pull request closed without merging**
