### PR TITLE
Locked mode

### PR DESCRIPTION
**Pull request by Varkal**
Implements #47

### CODE REVIEW

**Comment by Rayji96** [comment]
Can you add a screenshot for how this looks?

**Comment by Rayji96** [comment]
There's a linter issue :(

**Comment by Varkal** [comment]
> There's a linter failure :(

SuperLinter just say there is an error.... but don't say what or where :-D 

I don't find how to run the linter on my computer. `npx eslint` don't do anything, there is no `npm run lint` command. 
How do you do this ? 

> Can you add a screenshot for how this looks?

Capture d’écran 2021-06-02 à 08 52 18

There is a button with a padlock near the profile picture. The padlock is open/close to indicate the current state of the sheet

**Comment by Rayji96** [comment]
you'll have to configure the linters locally (VSCode has extensions that configure them nicely for you or have instructions on how to do so)

**Comment by Varkal** [comment]
Which extensions do you recommend ? What are your settings ? What is the rules ? 

If you can help me with that, i can provide another PR with npm script and/or documentation page to make contributions easier for other peoples :-)

**Comment by Varkal** [comment]
I see you add the linters configuration in .gitignore. Why ? How to ensure we will run the linters with the same rules enabled ?

**Comment by Rayji96** [comment]
These are the linters/extensions that are run on this project by SuperLinter that I have on vscode
image

The .gitignore ignores root level RC files which aren't even in the project to begin with lmao. I have no idea why I have that. I'll have to check my commit history to figure out what I was thinking

**Comment by Rayji96** [comment]
You're right though, I should put aside time to make a development onboarding README.
Incoming MRs should target the dev branch

**Comment by Varkal** [comment]
Thanks ! I will try to have the right setup on my local computer :-) 

Do you want me to rebase my branch and solve the conflict ?

**Comment by Rayji96** [comment]
yes please thank you :)

**Pull request merged**
