### PR TITLE
Cooler Looking Beastial Symbols

### PR DESCRIPTION
**Pull request by MarkusOzgur**
bestial-fail
bestial-fail-dsn

### CODE REVIEW

**Comment by Rayji96** [comment]
Can you show a screenshot of it on Dice So Nice and in the chatbox?
Also, did you make that yourself?

**Comment by Rayji96** [comment]
@MarkusOzgur I need to know for crediting and possibly legal reasons :)

**Comment by MarkusOzgur** [comment]
Screenshot_1

Oh sorry, didn't get a notification for whatever reason. I found it by googling, but AFAIK the vampire skull is from [VtR](https://whitewolf.fandom.com/wiki/Vampire:_The_Requiem?file=SkullVTR.png).

For some reason the skull's softness is a bit too much on the die, can fix it by thinning it maybe?

**Comment by Rayji96** [comment]
Oof. Can you get permission to use that icon? Don't want to get into hot water for using unowned assets haha

**Comment by MarkusOzgur** [comment]
Just messaged them, will let you know when they respond

**Comment by MarkusOzgur** [comment]
> Hello, thank you for contacting us about your project. Only World of Darkness logos, symbols, and other intellectual property are included in the Dark Pack fan content policy. This includes Vampire: The Masquerade, Werewolf: The Apocalypse, Mage: The Ascension, and other games. 
> 
> The policy does not include any Chronicles of Darkness logos, symbols, or intellectual property: please do not use art or content from Vampire the Requiem, Werewolf the Forsaken, Mage the Awakening, or any other Chronicles of Darkness game. (And mixing World of Darkness with Chronicles of Darkness art and content is also not allowed in the policy.)

Well... I guess not then. I will be working on a vampire skull myself then lmao

**Comment by Rayji96** [comment]
Hey let me know any updates :)

**Comment by Rayji96** [comment]
Going to close this unless any new updates :)

**Pull request closed without merging**
