### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by Lemantia**
Some translations were wrong. See list below:
- Background: "fond" should be "historique". "Fond" is a background in a movie scene kind a way. "Historique" is the word used in the french corebook.
- Rollable: "enroulable" should be Jet de dès. "Enroulable" means that you can roll something up, like a carpet.
- Rolling remorse: "jeté de remords" should be "jet de remords", simple typo.
- Messy critical: "Succès triomphal" should be "Triomphe Brutal". "Succès triomphal" sounds like a great thing to happen, it's a "triumphant success", the correction is the official one from the french corebook.

### CODE REVIEW

**Comment by paercebal** [comment]
Hello,

Small typo. In:

- Rollable: "enroulable" should be Jet de dès. "Enroulable" means that you can roll something up, like a carpet.

Actually, it should be "Jet de dés" (with the 'e' inside 'des' being 'é', not 'è').

**Comment by Dakayl** [comment]
There is still few typos : 
Attributes -> Attributs
Attribute -> Attribut

We can also add the translation of CustomRolls (Jets personnalisés)

**Comment by Rayji96** [comment]
Thank you for your work! I'll merge when the mentioned typos are addressed. :)

**Comment by Varkal** [comment]
IMHO, there is two more translations to fix : 

- "Boons", is translate by "Dettes" in the official rulebook
- "Oblivion", as not been translated yet by Arkhane Asylum (the company publishing the french version of V5). As "Obténébration" is only a partial translation, covering the Lasombra part of the Discipline, but not the Hecata part. I recommend using the english word. Oblivion is fairly understandable for french people (at least me and the people i've asked the question 😄  ). 

I can open a PR for those, but, as this one is open, maybe @Lemantia  can add them it ?

**Comment by Lemantia** [comment]
I believe those are already included when i updated the translation the second time, but i might have done it wrong ? Could you double check my file, and tell me if it's done ? 😅

About Oblivion, it's been translated as Néant in the companion on p34, so I used that. This is as close to an official translation as we have for now.

**Comment by Varkal** [comment]
@Lemantia Sorry, I hadn't checked the file, just read the comments. 
Everything is fine.

Thanks for pointing "Néant" to me. Seems like the official traduction for me a the moment

**Comment by Rayji96** [comment]
Can you also fix 
Attributes -> Attributs
Attribute -> Attribut

**Comment by Lemantia** [comment]
This should be good !

**Pull request merged**
