### PR TITLE
implement better humanity counter

### PR DESCRIPTION
**Pull request by erizocosmico**
Implements a humanity counter that works like the health and willpower bars, with + and - to increment and decrement humanity and better UX for marking stains.

Also fixed a handful of spanish translations.

### CODE REVIEW

**Comment by Rayji96** [comment]
Can you show a screenshot of stain marking?
+ and - are used to increment and decrement max health and willpower. I think it would be confusing for humanity to have that as well as max humanity never changes

**Comment by erizocosmico** [comment]
Screenshot 2021-11-06 at 19 52 46

+ and - increment and decrement current humanity and you can mark stains only on the empty boxes.

Right now, when you click on an empty box it increments your humanity by 1 so you have to convert one of the humanity boxes into a stain by clicking again on it, which I think is much more confusing and inconvenient.

**Comment by Rayji96** [comment]
I agree with that. I think the proper workflow should be empty boxes can be toggled to stain and then filled while filled boxes toggle to empty since you stain humanity much more often than you gain it.
In regards to the + and -, I still think it would be confusing to have those symbols control max health and willpower while it controls the value of humanity. A common confusion I've heard is that players are using + and - and confusing the max change as a value change. It's why I hid it behind the lock in the most recent update.

**Comment by erizocosmico** [comment]
It still feels a little bit wonky UX-wise. If you have 6 humanity and 2 stains and you click on the last stain it will become 7 humanity and 1 stain and then you have to go and click on the humanity box to turn it empty, which is on the left instead of on the right.

**Comment by Rayji96** [comment]
Hmmmmm. I'm very used to the clicking and Health and Willpower are click bound as well. Maybe a setting to toggle between clicking for all values or + and - for all values? IDK, I agree that Humanity feels funky but sheet consistency is really important imo

**Comment by Rayji96** [comment]
I'm open to suggestions :)

**Comment by erizocosmico** [comment]
Superseded by #120

**Pull request closed without merging**
