### PR TITLE
Blood Potency, automatic power dice addition to Discipline Rolls

### PR DESCRIPTION
**Pull request by MarkusOzgur**
I tried to use the initial array you had used for the HTML, but apparently, you can't directly call variables from that array because it is assigned by the getData() method... at least that's what the people on discord told me.

I created another array-just containing the numbers- to call the dice from there, I will also be using that table for some future implementations- like automatic Blood Surge, Mending, and other blood powers.

### CODE REVIEW

**Comment by MarkusOzgur** [comment]
I thought about getting the string of the HTML <p> and substringing the number out but I don't know much HTML and wasn't able to do it. The array table is better anyways 😒

**Comment by Rayji96** [comment]
Why did you close?

**Comment by MarkusOzgur** [comment]
Reopened it!

**Comment by Rayji96** [comment]
Merge conflicts :(

**Comment by MarkusOzgur** [comment]
Should be good I think

**Pull request merged**
