### PR TITLE
Crcr/dice tray

### PR DESCRIPTION
**Pull request by crcroberts**
Adds an optional (enabled by settings) dice tray at the bottom of the chat pane, allowing a user to construct and roll dice pools on characters they own without opening the character sheet

- Available characters are limited to those owned by a player
- Custom dice pools can be built out of any two Attributes, Skills, or Disciplines. Alternatively, one of the pools can be set to empty to roll a single stat.
- Disciplines that can be added to a pool are restricted to those owned by the character selected
- Attribute/Skill/Discipline dropdowns can either be sorted alphabetically or by order on character sheet, controlled by a second setting option.
- All dropdowns filterable (technical note: not actually dropdowns, since even in 2021 datalists are terrible 😢) 
- Shortcuts to Rouse, Willpower, Frenzy, and Remorse/Humanity checks also exposed for selected character
- Limited (as in I tried to do more than just google translate, but ultimately I am only fluent in english) localizations for appropriate strings
- dice svg is based off d10 icon in dice-so-nice (which is cc with attribution)
- green marble background is a photo of a trivet i own (which i originally purchased because it reminded me of the old vampire books 😄)

### CODE REVIEW

**Comment by Rayji96** [comment]
Can you show a screen shot?

**Comment by crcroberts** [comment]
Screenshot:
Dice tray

I'll have to take a look at what linting failures exist...

**Comment by Rayji96** [comment]
failed linter tests :(

**Comment by Rayji96** [comment]
How do you feel about making this a V5 module on FoundryVTT?
I don't mind merging this but some users may see this as superfluous/clutter

**Comment by Rayji96** [comment]
Sorry for the late suggestion :(

**Comment by crcroberts** [comment]
Nah, its expected feedback, that's why I made it so it could be enabled/disabled in the settings (disabled by default).
If you think that that's still gonna be an issue, I'll look into converting it to a module

**Pull request merged**
