### PR TITLE
use dots to represent attribute and skill values

### PR DESCRIPTION
**Pull request by erizocosmico**
This commit adds support for representing attribute and skill
values as a set of dots, just like the paper character sheet.

Final result:
Screenshot from 2021-02-07 14-53-26

### CODE REVIEW

**Comment by Rayji96** [comment]
Where did you find numLoop? I'm scouring the API and I can't find it

**Comment by Rayji96** [comment]
Thank you for your contribution! This is such a good implementation.

**Comment by Rayji96** [comment]
During my tests, I found that changing values does set the input field, it doesn't actually change the values in the actor object. Is this mirrored on your branch?

**Comment by Rayji96** [comment]
I've fixed the bug on branch rji/dev :)

**Comment by erizocosmico** [comment]
If i remember correctly the values were changed in the actor for me. I tried refreshing the app and exiting and entering the game world again and the values stayed there, which I thought was weird because i wasn't setting anything but I figured foundry was doing some magic with the forms by itself :smile:

**Pull request merged**
